### PR TITLE
Socket cpp

### PR DESCRIPTION
**Pull request by smlim991**

### CODE REVIEW

**Comment by DanShafman** [comment]
In the future let's open pull requests for finished code, please

**Comment by JinZSu** [comment]
what does that mean?

**Comment by DanShafman** [comment]
It means the stuff that was in gcs_code wasn't finished code, it was some demo code that wasn't fully functional yet. Let's merge our branches into master once we know our code is operational.

**Comment by JinZSu** [comment]
how do you upload without merge. just push and pull to branch?

**Comment by DanShafman** [comment]
That's right, just push your code to the socketCPP branch for now and once we know it works then we'll merge it into master.

**Comment by DanShafman** [comment]
Remember, this whole branch is meant to represent one full feature of the robot code. We should only merge a finished, functional feature back into master.

**Pull request closed without merging**
